---
language: python

os: linux

script:
  - echo "travis_fold:start:HELLO folding starts"
  - echo "hello world"
  - echo "travis_fold:end:HELLO folding ends"
  - echo "Test123..." && echo -en "travis_fold:start:test123\\r"
  - ./bash/travis_testing.sh
  - echo -en "travis_fold:end:test123\\r"
  - echo "TestABCDEFG..." && echo "travis_fold:start:testabcdefg"
  - ./bash/travis_testing.sh
  - echo "travis_fold:end:testabcdefg"
