#!/bin/bash

name=$1
statement=$2

name_lower=$(echo "$name" | tr '[:lower:]')

#echo "$name..." && echo -en "travis_fold:start:$name_lower\\r"
echo "$name..." && echo "travis_fold:start:$name_lower"
eval "$2"
echo "travis_fold:end:$name_lower"
