#!/bin/bash

name=$1
statement=$2

# name_lower=$(echo "$name" | tr '[:lower:]')

echo "$name..." && echo -en "travis_fold:start:$name\\r"
# echo "$name..." && echo "travis_fold:start:$name"
eval "$2"
echo -en "travis_fold:end:$name\\r"
